#ifndef RIPES_GRAPHICS_DEFINES_H
#define RIPES_GRAPHICS_DEFINES_H

namespace ripes {

#define TOP_MARGIN 20
#define BOT_MARGIN TOP_MARGIN
#define SIDE_MARGIN TOP_MARGIN

#define IO_MIN_SPACING TOP_MARGIN / 2
#define IO_PIN_LEN SIDE_MARGIN / 2

#define SHADOW_OFFSET SIDE_MARGIN / 8
#define SHADOW_WIDTH 1

#define BUTTON_INDENT 2
}
#endif  // RIPES_GRAPHICS_DEFINES_H
